export const Media = [
    {type: 'video', url: require('../assets/video/video1.mp4')},
    {type: 'video', url: require('../assets/video/IMG_22.mp4')},
    {type: 'video', url: require('../assets/video/mountain.mp4')},
    {type: 'video', url: require('../assets/video/louis_vuitton.mp4')},
    {type: 'video', url: require('../assets/video/medicine.mp4')},
    {type: 'video', url: require('../assets/video/tablet.mp4')},
    {type: 'video', url: require('../assets/video/amina.mp4')},
    {type: 'video', url: require('../assets/video/BARBER.mp4')},
    {type: 'video', url: require('../assets/video/interview.mp4')},
    {type: 'video', url: require('../assets/video/rustem.mp4')},
    {type: 'video', url: require('../assets/video/shine.mp4')},
    {type: 'video', url: require('../assets/video/barber2.mp4')},
    {type: 'video', url: require('../assets/video/shoes.mp4')},
    {type: 'video', url: require('../assets/video/IMG_6524.mp4')},
    {type: 'video', url: require('../assets/video/IMG_7944.mp4')},
    {type: 'video', url: require('../assets/video/IMG_9119.mp4')},
    {type: 'video', url: require('../assets/video/IMG_9120.mp4')},
]